### ISSUE TITLE
ace dragdrop_handler How to use

### ISSUE THREAD

**Issue by neo-hu** [ajaxorg/ace#2513] opened 2015-05-26 14:24 UTC
ace dragdrop_handler How to use

**Comment by nightwing** [comment] 2015-05-26 14:26
What do you mean? dragdrop_handler handles dragging selected text and droping text on the editor.

**Comment by nightwing** [comment] 2015-05-31 12:52
@neo-hu  i am closing this since it is not a bug report, but please feel free to comment with more details, if you still have a question, and i'll try to answer.

**Closed by nightwing** 2015-05-31 12:52 UTC
Labels: question
