### ISSUE TITLE
Arrow keys do not work after typing with non-English IME

### ISSUE THREAD

**Issue by renkun-ken** [ajaxorg/ace#2258] opened 2014-11-26 04:41 UTC
In normal condition, each time I input some non-English characters with IME the editor no longer responds to arrow keys (Up, Down, Left, Right) to move the cursor.

For example,

```javascript
var addResult = add(3, 2);
console.log(addResult);
```

When I type something like

```javascript
console.log("计算结果"); // after typing any such Chinese characters, the arrow keys no longer work.
```

**Comment by tylerlong** [comment] 2015-04-22 13:49
Same problem here. Actually you don't need to type anything in order to reproduce this issue. Just press Alt - Space to switch input method. http://ace.c9.io/build/kitchen-sink.html

Windows 8.1 64 bit, Chrome

**Comment by ghosert** [comment] 2015-07-11 12:19
Yes, please, this is a bug for Windows 8.1, and it happens when switching input method like @tylerlong said, I don't see it's fixed in the latest ace 1.2.0

It will be easier to reproduce this bug If you install another input method like sogou_pinyin here http://cdn2.ime.sogou.com/d5acb4356b6c9088c37f67be62490cdc/55a10805/dl/index/1435909316/sogou_pinyin_76f.exe

So that when you switch sogou input method and Microsoft Pinyin, the issue should be reproduced. In my computer the shortcut key to switch input method is "Windows Key + Space"

**Comment by nightwing** [comment] 2015-07-11 13:01
@ghosert that link gives Access Denied.  
On which site do you test? I can reproduce this issue only when there is an event listener calling preventDefault for "Windows Key + Space" and do not see this issue on http://ace.c9.io/#nav=about

**Comment by ghosert** [comment] 2015-07-11 14:25
I tested http://ace.c9.io/build/kitchen-sink.html and http://ace.c9.io/#nav=about, both pages have the issue. 

And not sure whether or not you can recognize Chinese, but I've uploaded the install file to my dropbox, you could download it here: https://dl.dropboxusercontent.com/u/30301809/sogou_pinyin_76f.exe

After installing, go to kitchen-sink page, input  some text and switch input method by pressing "windows + space", and then press any arrow key, it doesn't work anymore.

**Comment by ghosert** [comment] 2015-07-11 17:28
Just debugged ace.js, it seems there are two way to make arrow keys work. Please help to confirm whether the changes are safe. Thanks @nightwing 

In ace.js function named normalizeCommandKeys(callback, e, keyCode) 

### Option 1: Comment out this code snippet

```
    if (!useragent.isMac && pressedKeys) {
        if (pressedKeys[91] || pressedKeys[92])
            hashId |= 8;
        if (pressedKeys.altGr) {
            if ((3 & hashId) != 3)
                pressedKeys.altGr = 0;
            else
                return;
        }
        if (keyCode === 18 || keyCode === 17) {
            var location = "location" in e ? e.location : e.keyLocation;
            if (keyCode === 17 && location === 1) {
                if (pressedKeys[keyCode] == 1)
                    ts = e.timeStamp;
            } else if (keyCode === 18 && hashId === 3 && location === 2) {
                var dt = e.timestamp - ts;
                if (dt < 50)
                    pressedKeys.altGr = true;
            }
        }
    }
```

### Option 2: Add more lines

Under the code snippet above, add more lines like this:

```
    if (hashId === 8 && (pressedKeys[91] || pressedKeys[92])) {
        hashId = 0;
    }
```

@nightwing could you please which one is good to you ? Or any impacts if I go with either option ? Tested on win8, seems working.

**Comment by nightwing** [comment] 2015-07-11 18:27
@ghosert thanks for debugging this!

Looks like keyup for windows key event is never fired when pressing `win+space`, and every key after that is treated as cmd-key.

Both options above will disable binding to keys like `super-ctrl-left` on windows,  which is a  pity since `super-` keys are used in sublime keybindings and on Cloud9.

but if there is no other workaround we'll have to remove
```
        if (pressedKeys[91] || pressedKeys[92])
            hashId |= 8;
```
lines, from the first code block

**Comment by ghosert** [comment] 2015-07-12 01:32
Thanks for reply. Not familiar with sublime, have a try on Cloud9, the super-ctrl-left is used to switching tab right?

If that is the case, guess switching input methods happens more frequently, which the user can't afford to lose arrow keys in my case.

Will follow your suggestion first to comment out those two lines above. Hope one day you have the official fix for this.

Thanks.

**Comment by nightwing** [comment] 2015-07-14 20:28
I agree that switching input methods happens more frequently, and we should remove support for super modifier if there is no other solution.
https://github.com/ajaxorg/ace/tree/win-key seems to work, please test it at
https://rawgit.com/ajaxorg/ace/win-key/kitchen-sink.html

**Comment by ghosert** [comment] 2015-07-16 12:49
Yes, I can confirm the fix is working. When will this fix be merged to main stream ?

**Closed** 2015-09-03 17:02 UTC
