### ISSUE TITLE
Flickering/overlapping Chinese text during input method composition (IE only)

### ISSUE THREAD

**Issue by huanlin** [ajaxorg/ace#3622] opened 2018-03-23 10:58 UTC
I recorded an video to show this issue:

https://youtu.be/o1E5il2aFBg

This issue seems happens only with IE. Chrome is fine.

**Comment by huanlin** [comment] 2018-03-31 07:15
Does anyone have ideas about this issue?
If the video doesn't provide enough information, I can further explain.

**Comment by nightwing** [comment] 2018-03-31 21:13
looks like ie has a bug applying `background: inherit;` to a textarea, when there is lower precedence rule applying different background.

As a temporary workaround use

```css
.ace_text-input.ace_composition {
    background: white !important;
    color: black !important;
}
```

**Comment by RickStrahl** [comment] 2018-04-02 21:02
Thanks @nightwing,

I'm not sure I understand how this affects the render layout of word wrapping in the editor? Can you explain how background and color would affect the word wrapping behavior?

Either way gave this a shot and and added it to the stylesheet we use for ACE and I don't see a difference in the rendering - as before for me the the breaks render but at much wider widths than adequate between non-chinese symbols.

I also see this failing both in Markdown Monster (IE Hosted), IE as well as Chrome. In all places I pretty much see the same behavior:

Here's inside of MM:

![image](https://user-images.githubusercontent.com/1374013/38215918-eb2dfb84-3664-11e8-80ad-e999ddbd905a.png)

Here's Chrome:

![image](https://user-images.githubusercontent.com/1374013/38216008-2abbf756-3665-11e8-9ce3-bb6dc9e2f1fd.png)

It seems that this is not isolated to IE...

**Comment by nightwing** [comment] 2018-07-27 22:46
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by huanlin** [comment] 2018-07-28 01:20
@nightwing , thanks for the update. The overlapping effect is gone, but another issue is raised.
It seems automatically accept default words during Chinese input composition. Shown as the figure below: 

![ace-issue-input-chinese](https://user-images.githubusercontent.com/605065/43351602-f0ebf722-9246-11e8-85e1-f6f4741c3326.gif)

**Comment by nightwing** [comment] 2018-07-28 15:20
Thanks for checking.
Please try https://rawgit.com/ajaxorg/ace/ie11-ime/kitchen-sink.html, it should fix this issue too.

**Closed** 2018-07-31 17:45 UTC
Labels: ime

**Comment by huanlin** [comment] 2018-08-01 01:41
@nightwing , sorry for late. It works like a charm now. Thanks a lot!
