### ISSUE TITLE
Press space insert 4 spaces

### ISSUE THREAD

**Issue by Clemweb** [ajaxorg/ace#3766] opened 2018-09-09 10:14 UTC
Hi,

I don't understand this behavior : when I press space bar the editor insert 4 spaces.

Here is my configuration 

```js
editor = ace.edit("cw-edit-theme-file-editor");
		ace.config.set('basePath', '../app/javascript/ace');
    ace.config.set("workerPath", "../app/javascript/ace");
		editor.setReadOnly(false);
		editor.setOption("maxLines", 100);
		editor.setShowInvisibles(true);
		editor.setOptions({ tabSize: 4, useSoftTabs: true });
		ace.config.loadModule("ace/ext/emmet", function() {
      ace.require("ace/lib/net").loadScript("https://cloud9ide.github.io/emmet-core/emmet.js", function() {
        editor.setOption("enableEmmet", false);
      });
  	});
    ace.config.loadModule("ace/ext/language_tools", function() {
      editor.setOptions({
        enableSnippets: true,
        enableBasicAutocompletion: true
      });
    });
```

How to disable this ?

Thanks

**Comment by nightwing** [comment] 2018-09-09 13:12
I am unable to reproduce the issue, do you see it on http://jsbin.com/tixamoceru/edit?html,output?

**Comment by Clemweb** [comment] 2018-09-09 13:54
No it's ok on our test.

Any idea on what can do this ?

**Comment by Clemweb** [comment] 2018-09-09 14:00
it's seems editor.setOptions({ tabSize: 4, useSoftTabs: true }); posing problem
If I set false useSoftTabs, space are good but Tab doesn't work....

Any suggestion ?

**Comment by nightwing** [comment] 2018-09-09 14:40
It is hard to guess what can caused the issue based on information i have so far.

Which version of ace do you use? Are there any errors in the browser console?
Could you share a page where this happens, or try to change the jsbin example above to reproduce the issue?

**Comment by Clemweb** [comment] 2018-09-09 15:28
I can"t reproduce the bug, I've no error in console, I use the last no-conflict version.
Is it possible that another script is conflicting ? (bootstrap, jquery,etc ?) or css script ?
Only the tab is buggy all working fine...

**Comment by nightwing** [comment] 2018-09-09 16:28
try adding breakpoints at https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L13819 and https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L13787 and see what is called and with what arguments.
And check if `if (text == "\t")` on line https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L13735 is not changed in your version of code (loading ace from github or cdn is a simple way to do this)

**Comment by nightwing** [comment] 2018-09-10 09:03
> The bug is only produce with ace.js minify

that means some combination of minifier and a proxy replace "\t" on the line 13735 with " "
What do you use to minify ace.js?

**Comment by Clemweb** [comment] 2018-09-10 09:46
I use minify from https://github.com/mrclay/minify

**Comment by nightwing** [comment] 2018-09-12 09:06
This must be an issue with the minifier, try testing it with: `if (" " == "\t") console.log("error")`

**Comment by nightwing** [comment] 2018-09-20 17:35
Closing as this is likely not related to ace, please comment if you think this is an issue with ace and not the minifier.

**Closed by nightwing** 2018-09-20 17:35 UTC
