### ISSUE TITLE
PHP: Unsupported if: else: endif: endforeach;

### ISSUE THREAD

**Issue by tecnoweb** [ajaxorg/ace#5170] opened 2023-05-15 19:39 UTC
### Describe the bug

If I try to parse if($variale == true): return true; else: return false; endif;
the editor not recognize the part of stack code
the same issue is applied on
foreach($variable as $key):

endforeach;
the editor not recognize the part of stack code

### Expected Behavior

not parse this part of code

### Current Behavior

I don't have error but not parse this part of code

### Reproduction Steps

foreach($variable as $key):

endforeach;

if($variale == true): return true; else: return false; endif;

### Ace Version / Browser / OS / Keyboard layout

latest/Safari/Mac/IT

**Comment by InspiredGuy** [comment] 2023-05-16 11:10
hey @tecnoweb, thanks for the report. can you reproduce the issue in the [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) with PHP mode on? when I paste the code from the issue there, it gets syntax highlighting (see screenshot, made with Dracula theme enabled). Also, which theme are you using? Try using a different theme to see if syntax highlighting becomes visible.
![image](https://github.com/ajaxorg/ace/assets/1381598/65157db7-08d9-41dd-afee-558866cc57f7)

**Comment by tecnoweb** [comment] 2023-05-16 12:02
I try show you,
Not detect end of variable
foreach($variable as $key)**:**
if($variale == true): 
    return true; 
    else:
    return false; 
    endif;
endforeach;


```
Detect variable **{**
foreach($variable as $key) {
if($variale == true){
    return true; 
} else {
    return false; 
   }

}
```
<img width="473" alt="Screenshot 2023-05-16 alle 14 00 25" src="https://github.com/ajaxorg/ace/assets/1241963/a8d4e880-e9fa-43c5-8e05-6ec8c8fd6437">
<img width="399" alt="Screenshot 2023-05-16 alle 14 00 20" src="https://github.com/ajaxorg/ace/assets/1241963/28eb1de7-d001-40b8-8801-77d2b5ada16f">
<img width="582" alt="Screenshot 2023-05-16 alle 14 00 14" src="https://github.com/ajaxorg/ace/assets/1241963/8b441de5-bc47-432f-9232-0d5e66aed2de">

<img width="899" alt="Screenshot 2023-05-16 alle 14 00 39" src="https://github.com/ajaxorg/ace/assets/1241963/8c9f6dc0-3fe1-497a-aa1c-51ede05b817a">

**Comment by InspiredGuy** [comment] 2023-05-16 13:40
This is how I understood the issue, please correct me if I'm wrong: ace PHP mode does not recognise [alternative syntax with colons](https://www.php.net/manual/en/control-structures.alternative-syntax.php) as nested code and does not show the folding controls, and does not highlight closing tag (e.g. `endforeach;`) as a closing brace. I can reproduce it in the kitchen sink.

**Comment by InspiredGuy** [comment] 2023-05-16 13:55
This might be fixed by using [pythonic](https://github.com/ajaxorg/ace/blob/master/src/mode/folding/pythonic.js) folding mode for PHP (since it also handles nested code structures without braces), or mixing CStyle folding mode with pythonic one using [mixed](https://github.com/ajaxorg/ace/blob/master/src/mode/folding/mixed.js) folding mode, or implementing PHP folding mode which would handle both cases - I am not sure which would help, these are listed in order of approximate effort required. Folding mode would be used in the [PHP mode](https://github.com/ajaxorg/ace/blob/master/src/mode/php.js). Contributions are welcome!

**Comment by tecnoweb** [comment] 2023-08-18 09:54
I have try to add some modification but unable to do it can you help me ?

**Comment by InspiredGuy** [comment] 2024-03-27 09:44
https://github.com/ajaxorg/ace/pull/5491 with a fix was merged, should be available in the next release

**Closed by InspiredGuy** 2024-03-27 09:44 UTC
Labels: p2, effort/medium, bug
