### ISSUE TITLE
scss sintax highlighting

### ISSUE THREAD

**Issue by MikBin** [ajaxorg/ace#2584] opened 2015-07-03 15:14 UTC
Hi,
sintax highlighting for sass scss is not working.
is there any particular plugin configuration to use?
thanks

**Comment by nightwing** [comment] 2015-07-03 16:08
What exactly doesn't work?
Modes for sass and scss are at https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/sass.js  https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/scss.js.

**Comment by MikBin** [comment] 2015-07-04 08:37
hi
it simply doeasn't highlights. everything is in white color.
I've to set less to have some kind of highlighting

2015-07-03 18:08 GMT+02:00 Harutyun Amirjanyan <notifications@github.com>:

**Comment by nightwing** [comment] 2015-07-04 09:53
It works in http://plnkr.co/edit/3GSCNtY9060FBslNRn2y?p=preview, try to create a demo showing the issue

**Comment by MikBin** [comment] 2015-07-05 11:19
there are some js errors in console. it fails to importScripts
maybe I've to reinstall cloud9 or just some module
I'm going to figure it out
thanks

2015-07-04 11:53 GMT+02:00 Harutyun Amirjanyan <notifications@github.com>:

**Comment by nightwing** [comment] 2015-07-05 12:24
Are you installing https://github.com/c9/core?

I am closing this issue since it is not a bug in Ace, but feel free to comment if you have more questions

**Closed by nightwing** 2015-07-05 12:24 UTC

**Comment by MikBin** [comment] 2015-07-05 12:41
yes I'm installing c9/core
maybe I've posted the bug in the wrong section
sorry
and many thanks

2015-07-05 14:24 GMT+02:00 Harutyun Amirjanyan <notifications@github.com>:
