### ISSUE TITLE
Undo not working on Mac

### ISSUE THREAD

**Issue by rahmanusta** [ajaxorg/ace#2416] opened 2015-03-24 09:41 UTC
We  are using Ace in AsciidocFX. We have some problems with some keyboard types (e.g. german, french)

For example in this scenerio, Command Y and Command Z reversed.

https://github.com/asciidocfx/AsciidocFX/issues/61

I want to handle all shortcuts with jquery hotkeys or Mousetrap like libraries. How can i do that?

Thanks.

**Comment by nightwing** [comment] 2015-03-24 18:25
> I want to handle all shortcuts with jquery hotkeys or Mousetrap like libraries. How can i do that?

You can add a capturing event listener and call `editor.execCommand`, but maintaining the list of commands will be a lot of work.

Is this issue with Command Y and Z being reversed reproducible on ace.c9.io or does it happen only in embedded version?
I've tried german keyboard layout with mac 10.6 Safari 6 and the key which types z triggers command-z

**Comment by rahmanusta** [comment] 2015-03-24 20:06
It is about JavaFX embedded webview.

I'm thinking so;

1) Disable all/or some shurtcuts
2) Write your own shortcut handler
3) Pass own handler events to ace with exec command.

How can i do that? Or do you have another suggestion?

Thanks

**Comment by nightwing** [comment] 2015-03-24 21:45
If it's bug in JavaFX webview how are you going to get the correct keycode from event?
To disable all shortcuts you can do `editor.commands.commandKeyBinding = {}`, but then you need to reimplement all of the https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js.
Instead of that you can call keyboard handler of Ace with corrected event, which will be much simpler
Only needs to override  [editor.onCommandKey](https://github.com/ajaxorg/ace/blob/a2e05ac438e9021d0858f3dffb51fbc2b719d812/lib/ace/editor.js#L1026-L1028) function

**Comment by rahmanusta** [comment] 2015-03-24 21:55
It is not bug JavaFX bug, I think it is related to ace.

I only need to override already shortcuts, not implementation. Implementations are OK, problem for binding.

For example, I want to bind like below hook for "ctrl+z"

$(document).bind("ctrl+z",function(){
  // call ace's undo implementation
}),

When i using like that, Ace is not passing event to my binding.

**Comment by nightwing** [comment] 2015-03-24 22:25
Use capturing event listeners or use `editor.keyBinding.$handlers = []`.

```js
$(document).bind("ctrl+z",function(){
    editor.execCommand("undo")
}),
```

**Comment by rahmanusta** [comment] 2015-03-25 15:40
I did it below;

```javascript
editor.keyBinding.$handlers = [];

$(document).bind('keydown', 'ctrl+z', function(){
    console.log("undo");
    editor.execCommand("undo")
});
$(document).bind('keydown', 'ctrl+y', function(){
    console.log("redo");
    editor.execCommand("redo")
});
```

And it doesnt invokes hooks. When I debug in chrome dev console, Im seeing event listeners on textarea. Ace is not passing events to that callbacks.

**Comment by nightwing** [comment] 2015-03-25 16:56
Well, jquery hotkeys doesn't intercept events when textarea is focused, you need to configure it for that, also you need to preventDefault event to cancel default action in textarea.
see http://plnkr.co/edit/3GSCNtY9060FBslNRn2y?p=preview.
But this the only difference between [jquery.hotkeys](https://github.com/jeresig/jquery.hotkeys/blob/master/jquery.hotkeys.js#L157) and Ace is that Ace uses e.keyCode instead of e.which, which are same on all browsers.

**Comment by rahmanusta** [comment] 2015-03-25 17:29
This great work, thanks

**Comment by nightwing** [comment] 2015-03-27 21:54
Closing since from https://github.com/asciidocfx/AsciidocFX/issues/61 it appears this was not related to Ace and jquery have the same bug. @rahmanusta please let me know if i misunderstood and there is anything Ace can do here.

**Closed by nightwing** 2015-03-27 21:54 UTC

**Comment by rahmanusta** [comment] 2015-03-27 23:18
Yes your words true @nightwing . That was a JavaFX bug for AZERTY keyboards. Thanks for your really helpful support.

**Comment by xzel23** [comment] 2018-03-11 13:15
Since I have this issue now (QWERTZ keyboard) and you said that it's a JavaFX bug for AZERTY keyboards, can you point me to the JavaFX bug report? Or has this not yet been reported? Then I'd file a report myself. Bugs won't get fixed unless reported to the devs.
