### ISSUE TITLE
Ace scrolls when on focus

### ISSUE THREAD

**Issue by webchaz** [ajaxorg/ace#2963] opened 2016-05-05 18:26 UTC
We're loading ace within a scrollable modal window and clicking on the ace editor, it scrolls up about 100px.  Any idea how to disable this?

**Comment by tothandras** [comment] 2016-05-19 08:29
We have the same error, it also scrolls when editing.

**Comment by mike-strauch** [comment] 2016-06-09 23:18
Seems to be coming from [here](https://github.com/ajaxorg/ace/blob/fc9a2396afa9d091013c46dc73fdc117a87466fd/lib/ace/keyboard/textinput.js#L78-L88).

**Comment by kruny1001** [comment] 2016-06-23 02:59
+1

**Comment by kruny1001** [comment] 2016-06-23 03:09
Use version 1.2.3, After replacing thsi version, it doens't scroll up

**Comment by SvenSchoene** [comment] 2017-02-04 01:25
Even when using 1.2.3 we still have this issue... :(

**Comment by alphatesla** [comment] 2017-02-20 13:36
stille in error for me on 1.2.6

**Comment by nightwing** [comment] 2017-02-20 15:43
if you still see this issue with 1.2.6, please show a page where the issue can be reproduced

**Comment by otopsy** [comment] 2017-02-27 17:18
i've made a PR on this, because it was so annoying #3227

**Comment by lithiumlab** [comment] 2017-04-25 00:34
I can confirm this is happening only on editor boxes that are in the lower part of a large page.

**Comment by nightwing** [comment] 2017-04-25 18:25
Turns out this is caused by a bug in the behavior of position fixed, which works differently for children of nodes with transforms applied.

#3279 adds a workaround for that, but it needs some more work before it can be merged https://rawgit.com/ajaxorg/ace/scroll-bug/demo/scrollable-page.html

until this is fixed in the next version, please add
```
.ace_text-input {position:absolute!important}
```
somewhere in your css as a workaround.

merging this into https://github.com/ajaxorg/ace/issues/3245 since it had a better description of the issue

**Closed by nightwing** 2017-04-25 18:25 UTC

**Comment by lithiumlab** [comment] 2017-04-25 18:28
Great, thanks for the timely answer.
