### ISSUE TITLE
Bugs with "Show Line Numbers" & "Show Invisibles" in Kitchen Sink Demo

### ISSUE THREAD

**Issue by McPrescott** [ajaxorg/ace#3791] opened 2018-10-05 07:07 UTC
Noticed some strange behavior while playing with the kitchen sink demo. I'm currently using Firefox 62.0 on Ubuntu 18.04.

First image shows what I believe is correct behavior, with:
  + `Show Line Numbers = true`
  + `Show Invisibles = false`

![ajaxorg ace1](https://user-images.githubusercontent.com/20735042/46520223-6d2a1b80-c838-11e8-9a71-a5b7592deb20.png)

-----

Now when `Show Line Numbers = false`, a large margin appears on the left of the editor.  

![ajaxorg ace3](https://user-images.githubusercontent.com/20735042/46520372-fc373380-c838-11e8-8bdc-5a8e2a90f5cb.png)

-----

And finally with `Show Invisibles = false`, tabs and newlines are rendered properly, but all spaces disappear.

![ajaxorg ace2](https://user-images.githubusercontent.com/20735042/46520460-51734500-c839-11e8-98dc-3cdf239b2ec5.png)

-----

I'm new to this project, so I apologize if this issue has been posted inappropriately, or if its a duplicate. I did however spent time reading through issues, and could not find any addressing these specifically. I also checked to see if there was a list of supported browsers, or operating systems just to make sure Firefox/Linux Distros were supported (if operating system even makes a difference in this case).

**Comment by nightwing** [comment] 2018-10-08 18:55
Thank you for the detailed report! 

Please check if the issue is fixed on https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html

**Comment by McPrescott** [comment] 2018-10-18 20:14
I just checked out the new kitchen-sink demo, show line numbers is working correctly, and show invisibles is also working correctly now. There is however, some strange behavior occurring for me when `Show Invisibles = false`.

I'm really unsure of how to explain the behavior. The gif shows arrow key navigation, as well as removing and adding spaces. When adding spaces the the cursor was unaligned to the current column.

![ace-editor-screencast](https://user-images.githubusercontent.com/20735042/47180925-eb79c980-d2de-11e8-83e9-23b4bc3edaa3.gif)

**Comment by nightwing** [comment] 2018-10-25 19:42
Looks like the character for space is rendered at the half of the monospace character width with that font, could you try setting the fontFamily of the editor to some other monospace font?

**Comment by McPrescott** [comment] 2018-10-29 05:53
Good eye that was exactly what the issue was! After switching the font everything works normally :smile: Thank you for your help it is much appreciated. :+1:

**Closed** 2018-11-13 19:50 UTC
