### ISSUE TITLE
When you check "Enable Behaviours" for XML closing tags are added

### ISSUE THREAD

**Issue by idantr** [ajaxorg/ace#2809] opened 2015-12-14 13:40 UTC
in XML if write for example  the text "<tag" and add ">" in the end you automatically get  the text "</tag>"  added in the end
the bug is that is always works....
if i add the char ">" agter the first "g" in the following xml text
`<tag></tag>`

i get:    `<tag></tag>></tag>`    this is wrong.
regards
Idan

**Comment by lidortal** [comment] 2015-12-16 13:55
+1

**Comment by boghyon** [comment] 2017-11-30 11:45
+1 This seriously needs to be fixed. The closing tag is abruptly added without checking if the tag has already a closing tag or not.

![image](https://thumbs.gfycat.com/IncomparableGlossyFish-size_restricted.gif)

**Comment by nightwing** [comment] 2017-11-30 17:57
https://github.com/ajaxorg/ace/pull/3468 should fix both of these issues. (can be tested at https://rawgit.com/ajaxorg/ace/xml-behaviour/kitchen-sink.html)

But for the `<tag</tag>` it will still complete to `<tag></tag></tag>`, because there doesn't seem to be a good way to determine if the last  `</tag>` was closing the current tag or a parent one. Let me know if you think this needs to be tweaked more.

**Comment by boghyon** [comment] 2017-11-30 21:08
@nightwing Awesome, thank you for the quick fix. Not sure how commonly `<tag</tag>` would be typed (since such syntax is just invalid in XML) and there is definitely still room for improvements regarding XML behaviors but for now, I think this issue can be closed.

**Closed** 2017-12-17 10:54 UTC

**Comment by boghyon** [comment] 2018-01-21 15:54
@nightwing How are the releases managed in ace? Asking because the issue can still be reproduced in https://ace.c9.io/build/kitchen-sink.html. In which version can we expect the fix to be available?

**Comment by nightwing** [comment] 2018-01-21 20:55
this will be included in the next version, which most likely will be released by the end of coming week.
