### ISSUE TITLE
Deleting some utf8 characters in Ace requires two presses of backspace per character

### ISSUE THREAD

**Issue by STRd6** [ajaxorg/ace#2630] opened 2015-08-12 18:15 UTC
When I paste the following three utf-8 characters into Ace it takes two presses of backspace to delete each one.

```
👷🏼🚧
```

I expect that it should only take one backspace to delete each character.

**Comment by pamelafox** [comment] 2015-08-13 23:32
I just had a similar issue reported, where one backspace deletes 2 characters:
https://www.khanacademy.org/computer-programming/text-command-bug/6471292770451456
I replicated that on the ACE site as well.
Is that the same issue or shall I file a new issue?

**Comment by nightwing** [comment] 2015-08-13 23:53
@pamelafox this is same issue. It is caused by incorrect handling of astral Unicode symbols https://github.com/ajaxorg/ace/issues/2338, i'll try to fix it.

**Comment by nightwing** [comment] 2022-05-09 15:31
Sorry for the bot, but this issue have been fixed a long time ago by https://github.com/ajaxorg/ace/commit/45a67d166fa9b64b93587ce3c99158b6d0bd6a59. You can verify it on https://ace.c9.io/, Closing, but please tell if you find any follow-up defects. Thanks!

**Closed by nightwing** 2022-05-09 15:31 UTC
Labels: closing-soon
