### ISSUE TITLE
Android Delete

### ISSUE THREAD

**Issue by Go2sites** [ajaxorg/ace#4020] opened 2019-07-17 17:41 UTC
On Android if you delete with an empty space to the right side of the cursor it copies the entire line and drops it below. I am new to ace so not sure if i am missing something or this is a bug. Any ideas? i have had a good google search but found nothing.

**Comment by nightwing** [comment] 2019-07-17 20:11
Which phone and what keyboard are you using?

**Comment by Go2sites** [comment] 2019-07-17 20:20
Google Pixel 2, Daydream keyboard

**Comment by Go2sites** [comment] 2019-07-17 20:22
No Google GBoard

**Comment by nightwing** [comment] 2019-07-17 20:33
does this happen on ace.c9.io? i can't reproduce it there with chrome+gboard on samsung galaxy note

**Comment by Go2sites** [comment] 2019-07-17 20:35
Yeah it does

**Comment by Go2sites** [comment] 2019-07-17 20:39
just tested on a Huawei and it also does it on their

**Comment by Go2sites** [comment] 2019-07-17 20:40
The Huawei is also using Gboard

**Comment by Go2sites** [comment] 2019-07-18 07:33
Here is a vidoe to show what its doing:
https://drive.google.com/file/d/1-SFnDqUQojEirIhPCNHdn0T2TDEE53OW/view?usp=sharing

**Comment by nightwing** [comment] 2019-07-19 14:18
Thanks, the video was helpful, could you test if the issue is fixed on https://raw.githack.com/ajaxorg/ace/master/kitchen-sink.html?

**Comment by Go2sites** [comment] 2019-07-19 14:24
Hi yeah well done i can confirm that has fixed the issue.

**Closed** 2019-07-19 14:54 UTC

**Comment by Go2sites** [comment] 2019-07-20 12:50
When will the fixed update be available?
