### ISSUE TITLE
Get value from div php

### ISSUE THREAD

**Issue by Rapprogtrain** [ajaxorg/ace#3775] opened 2018-09-21 12:35 UTC
```
<div id="htmlEditor"></div>
<div id="line"></div>
<div id="cssEditor"></div>
<div id="line2"></div>
<div id="jsEditor"></div>
<div id="line3"></div>
</div>	
<div id="result-block">
<iframe id="result" frameborder="0"></iframe></div></div>
	<script src="js/app.js"></script>
		  </body>
		  </html>
			<script language="javascript">

var htmlEditor = ace.edit('htmlEditor');
var cssEditor = ace.edit('cssEditor');
var jsEditor = ace.edit('jsEditor');
var htmlSave = (localStorage.getItem("htmlSave"));
var cssSave = (localStorage.getItem("cssSave"));
  var jsSave = (localStorage.getItem("jsSave"));
    $.ajax({
        type: "POST",
        url: "index.php",
        data: { htmlSave: htmlSave, cssSave: cssSave, jsSave: jsSave }
    }).done(function(data) {
			console.log(htmlSave);
        });
</script>
<?php
if(isset($_POST['submit']))
{
	$htmlSave = $_POST['htmlSave'];
	$cssSave = $_POST['cssSave'];
	$jsSave = $_POST['jsSave'];
	$insert=$db->query("INSERT INTO `field`(`html_field`, `css_field`, `js_field`) VALUES ('$htmlSave',
	'$cssSave', '$jsSave')");
} ?>
```

**Comment by nightwing** [comment] 2018-10-09 12:14
closing as a duplicate of https://github.com/ajaxorg/ace/issues/3774

**Closed by nightwing** 2018-10-09 12:14 UTC
