### ISSUE TITLE
top of undefined error

### ISSUE THREAD

**Issue by Cellcote** [ajaxorg/ace#3707] opened 2018-07-12 14:51 UTC
We are running Ace editor 1.2.8 (did not yet update because we are awaiting a new release after #3640), and sometimes we run into the following error:

"Unable to get property 'top' of undefined or null reference\",\"filename\":\"ace\/ace.js\",\"lineno\":1,\"colno\":302097,\"error\":[\"TypeError: Unable to get property 'top' of undefined or null reference\",\"   at $moveTextAreaToCursor ace\/ace.js:1:302097)\",\"   at a (ace\/ace.js:1:65295)\",\"   at i (ace\/ace.js:1:20661)\"

In our situation, we have the possibility to open an ace editor instance in a modal, and from this modal, we can open more ace editor instance modals. We think this triggers only when a new instance is opened before the original editor is fully loaded, but we cannot constantly reproduce the issue. Any idea or pointers on how to avoid this issue?

**Comment by nightwing** [comment] 2018-07-16 21:43
This is caused by https://github.com/ajaxorg/ace/blob/v1.2.8/lib/ace/virtual_renderer.js#L633, and is fixed on master 
https://github.com/ajaxorg/ace/blob/e3a65e7578efd44afcc2c23b0788f31986fc0f52/lib/ace/virtual_renderer.js#L630, unfortunately there doesn't seem to be a way to avoid this without modifying the source code

**Comment by Cellcote** [comment] 2018-07-17 11:37
Thanks for your reply and your work. Any schedule on a 1.3.4 release yet?

**Comment by nightwing** [comment] 2018-08-06 10:07
Unfortunately fixing all the regression from innerHTML removal took longer than expected.
Version 1.4 was published today.

**Closed by nightwing** 2018-08-06 10:07 UTC
