### ISSUE TITLE
Make some portions of editor readonly

### ISSUE THREAD

**Issue by qburst-varunnath** [ajaxorg/ace#4515] opened 2021-06-21 05:43 UTC
I am using editor to edit html. I need to prevent editing text between tags containing a given attribute. For example below given I need to make the P tag and inside contents readonly since it contains the attribute **_data-readonly_**

`<p class="dummy" data-readonly>This is not editable </p>`

Could any one please help to find a solution for this

**Comment by andrewnester** [comment] 2022-05-10 12:37
closing as duplicate of https://github.com/ajaxorg/ace/issues/3634

**Closed by andrewnester** 2022-05-10 12:37 UTC
