### ISSUE TITLE
Option to highlight local variables in scope

### ISSUE THREAD

**Issue by anonyco** [ajaxorg/ace#3660] opened 2018-05-06 21:58 UTC
I love Ace. It is lickety fast, performant, and can handle huge files without problem. However, I currently choose to use CodeMirror for one and only one specific reason that makes CodeMirror far more practical: local variable scope highlighting. Basically, in CodeMirror, variables within the local scope get highlighted while variables not inside the local scope dont get highlighted. This is super helpful because it lets me know when I type in a non-existent variable.

**Comment by anonyco** [comment] 2022-05-09 21:53
I wish to leave this issue open. Thank you.

**Comment by akoreman** [comment] 2023-03-07 11:08
Closed as duplicate of issue #3500.

**Closed by akoreman** 2023-03-07 11:08 UTC
Labels: needs-triage, feature-request
