### ISSUE TITLE
"Looks good"

### ISSUE THREAD

**Issue by tmcw** [ajaxorg/ace#2294] opened 2015-01-03 00:56 UTC
The hardcoded default for line markers here: https://github.com/ajaxorg/ace/blob/d2b6b43679837ceced56be758f3bacc1e682d88a/lib/ace/ext/error_marker.js#L119-L122 - could this be removed so the code can fail instead? It's a hardcoded English string that could be removed, as well as a potential source of masked errors.

**Comment by nightwing** [comment] 2015-01-03 19:17
It is not hardcoded for all line markers but only for error markers which are shown with alt-e.
Why do you want that code to fail? it needs to show something when there are no errors in the document.

**Comment by nightwing** [comment] 2015-01-28 22:25
Closing since the "Looks good" marker is by design.
Please reopen if i misunderstood your bug report, and you still think this needs to  be changed

**Closed by nightwing** 2015-01-28 22:25 UTC
