### ISSUE TITLE
Editor not initialize properly

### ISSUE THREAD

**Issue by svkmedia** [ajaxorg/ace#4159] opened 2020-01-22 09:32 UTC
We are using ACE editor and everything works fine except when user gets log out and then re-login. Then editor loads really strange without visible content (see screenshot). Even line numbers have strange style with spaces...
All content is loaded via ajax. 
Any ideas what's wrong?
After full page refresh editor works fine

![Screenshot 2020-01-22 at 10 31 20](https://user-images.githubusercontent.com/8425765/72882138-5dbb3400-3d02-11ea-8b2d-2f6113cba1e4.png)

**Comment by nightwing** [comment] 2020-01-22 21:50
maybe editor resize is created when the container is not visible or is small, and then when container is resized `editor.resize` is not called.

You can try calling editor.resize, or using ResizeObserver to check if the issue is indeed caused by missing resize call something else.

```js
var observer = new window.ResizeObserver(function(e) {
    var rect = e[0].contentRect;
    editor.renderer.onResize(false, null, rect.width, rect.height)
});
observer.observe(editor.container);
```

**Comment by nightwing** [comment] 2020-04-14 11:19
Closing, but please comment if the suggestion above did not help to fix the issue.

**Closed by nightwing** 2020-04-14 11:19 UTC
