### ISSUE TITLE
Cursor position and line wrapping are wrong with proportional fonts.

### ISSUE THREAD

**Issue by matj1** [ajaxorg/ace#4586] opened 2021-11-27 14:55 UTC
When Ace editor uses a proportional font for the edited text, the cursor usually is in a wrong position, and the lines wrap wrongly. If the line contains narrow characters before the cursor, the cursor advances too fast for the line, so it's ahead of the place where the characters actually appear, and the line wraps too soon, because it's when the cursor reaches the end of the view, not the text.
If the line contains wide characters before the cursor, the cursor advances too slowly, so it's behind the place where the characters actually appear, and the line wraps too late, so some of the text is outside of the view. That makes the editor hardly useable with proportional fonts

I did a demonstration with Verdana Pro. Both lines 2 and 3 contain 80 characters, and both lines have a cursor at the end. The line with W's has the cursor displayed not far enough from the beginning of the line, and the line with i's has the cursor displayed too far from the beginning of the line. If I write some characters, they appear at the end of each line, which is not where the cursors are. Line 6 is wrapped too late, so “WWW21” and “WWW22” are outside of the view. Line 8 is wrapped too soon, so there is a lot of unused space at the end.

A picture of the demonstration:
![Screenshot_20211127_155234](https://user-images.githubusercontent.com/22873928/143686343-57ee1a32-f183-494b-8e7c-9c86a144ffa1.png)

Expected behaviour: The cursor is displayed exactly at the position where the characters appear when they are written, and the lines wrap just when the text reaches the width of wrapping.

**Comment by jorgk3** [comment] 2021-11-28 00:25
This was also reported for ThunderHTMLedit, a Thunderbird/[Betterbird](https://www.betterbird.eu/) add-on which uses Ace for HTML editing in the compose/Write window of the e-mail client.

**Comment by andrewnester** [comment] 2022-06-02 08:58
Closing as duplicate of https://github.com/ajaxorg/ace/issues/460

**Closed by andrewnester** 2022-06-02 08:58 UTC
Labels: needs-triage, bug
