### ISSUE TITLE
Cursor misaligned when using browser zoom tools on Safari 13.1 with MacOS 10.15.4

### ISSUE THREAD

**Issue by pdgessler** [ajaxorg/ace#4234] opened 2020-04-02 10:52 UTC
When using Safari on MacOS, if you use the browser page zoom set to something other than 100%, the Ace cursor becomes misaligned. So entered text is inserted at a different position than the cursor indicates. At browser zoom of 100%, everything works as expected.

This problem appears to be isolated to latest Safari (Version 13.1 (15609.1.20.111.8)) on the latest MacOS Catalina 10.15.4.

GIF of the problem in the Kitchen Sink:

![ezgif-7-fe249c2b54fa](https://user-images.githubusercontent.com/1495628/78240779-14772580-74a5-11ea-9c66-ad60593db49a.gif)

I work at Overleaf; our users first started reporting this problem the day that the Catalina update was released. After a number of reports, we were able to isolate this to usage of browser zoom. We have been suggesting the workaround of using Ace's font size option (which we have exposed to users in Overleaf) rather than the browser zoom.

We did not have any reports of this particular problem before Catalina 10.15.4 was out, so it appears to be something new with that combination of Safari and MacOS.

**Comment by nightwing** [comment] 2020-04-03 00:07
looks like ResizeObserver on safari doesn't rescale the contentRect with zoom. Could you please check if the issue is fixed on https://raw.githack.com/ajaxorg/ace/safari-broken-resize-observer/kitchen-sink.html ?

**Comment by pdgessler** [comment] 2020-04-03 06:18
@nightwing confirmed fixed, the cursor alignment problem does not appear in https://raw.githack.com/ajaxorg/ace/safari-broken-resize-observer/kitchen-sink.html with my Safari/MacOS setup. 👍

**Closed** 2020-04-03 10:04 UTC

**Comment by liantze** [comment] 2020-05-04 02:55
We continue to have users writing in about this. I've now tagged all the queries about this on Front with safari_zoom_issue; currently 101 messages.
