### ISSUE TITLE
IOS compatibility 

### ISSUE THREAD

**Issue by Gozala** [ajaxorg/ace#37] opened 2011-01-11 13:21 UTC
Ace could be a ideal editor on IOS devices (iPad, iPhone) if you just could type, but unfortunately virtual keyboard never shows up with ACE, also I believe someone had a patch for bespin to make that work. 
@gissues:{"order":96.27329192546586,"status":"backlog"}

**Comment by dai-shi** [comment] 2015-01-05 22:50
Hi, just for reference, I use ace for my project. The virtual keyboard issue is troublesome and I end up with making the editor to be content size. There might be a performance issue. 

https://github.com/dai-shi/codeonmobile

**Comment by staabm** [comment] 2015-02-17 11:03
This is still a Problem, seen on http://3v4l.org/

**Comment by benblo** [comment] 2015-02-18 07:40
This issue is also blocking PlayCanvas.com (iPad Air iOS 8), which is a shame because the rest if the editor fully supports the iPad, and overall is quite an insane showcase of what HTML5 can be!

**Comment by hjwp** [comment] 2015-02-18 10:50
+1.  currently investigating a workaround involving manually creating some scroll buttons, to sit next to the editor, using `scrollBy` http://ace.c9.io/#nav=api&api=virtual_renderer

**Comment by haches** [comment] 2015-03-02 11:46
+1

**Comment by zloylos** [comment] 2015-03-02 22:46
+1 for scrolling problems

**Comment by KyleBoyer** [comment] 2015-03-03 06:12
+1 for scrolling problems.

**Comment by ertug2** [comment] 2015-03-09 02:10
+1 for scrolling problems.

**Comment by iq77** [comment] 2015-03-10 17:23
Hello gusy, I'm not good / patient enough to fix the editor itself, since the whole concept of touch vs. mouse is different. But with the following script you can get ACE editor to scroll on touch devices (IOS / Android):

http://pastebin.com/1Rh7UDea

**Comment by tluyben** [comment] 2015-03-12 14:26
@iq77 What is that code supposed to do? I am trying it and so far it makes no difference? I'm one of the people who really would like this to work normally on touch devices...

**Comment by iq77** [comment] 2015-03-12 14:36
@tluyben on "touchstart" it saves the x/y coordinates of the touch event. On "touchmove" calculates the difference between start and end, then passes the x/y values to ACE's "renderer". The renderer does the scrolling. It works on my script, but maybe you have to adapt some class names etc. to your own needs.

**Comment by tumnus123** [comment] 2015-03-27 18:04
This is a great thread, but I found it difficult to tell (a) what the nature of the "scrolling issue" is, (b) what devices/OS versions are affected, and (c) what workarounds are available.  If someone would be willing to summarize where these are at, that would be superb.

I just tested the Kitchen Sink on  [iPad Air 2 running iOS 8 and Safari 8] and [Nexus 10 running Android 5.1 and Chrome 40], and was able to scroll both horizontally and vertically (in landscape; I did not test with devices in portrait orientation). Steps to repro:
1) Browse to http://ace.c9.io/build/kitchen-sink.html 
2) Add a bunch of lines (blank lines work fine) in the editor pane until there are more lines than will fit on the screen.
3) If needed, zoom out to view the full browser. (Editing the contents of the editor pane may automatically zoom you in, making it difficult to tell whether you're scrolling the pane or just moving the zoomed-in view around.)
4) Swipe up/down on the very right edge of the editor pane. No scrollbar will appear, but the editor pane contents should scroll as expected. 
5) To test hscroll, create a long string of characters that's wider than what will fit on the screen; zoom out if needed; swipe left/right on the very bottom edge of the editor pane.  I see a fading scrollbar on Android, but no scrollbar on iOS... but hscrolling works on both, regardless.

**Comment by barneycarroll** [comment] 2015-06-17 13:43
I've been searching through the issues and from what I can work out this is the definitive 'everything touch-related' thread. Correct me if I'm wrong and I'll keep digging / file a new issue.

iOS touch is seemingly unable to bring up the context menu in an Ace context (significantly, this allows cut + paste). Normally this can be triggered by tapping the cursor, but Ace overrides this behaviour to move the cursor forward by one character instead.

**Comment by AStoker** [comment] 2015-06-17 15:54
@barneycarroll, this does seem to be the touch related thread. I've been working recently trying to get at least some touch support implemented for scrolling. Right now, you can scroll if you scroll over just the right area in the far right or bottom of the editor viewspace (where the scroll bars would be). But that's not a viable solution.

I think I'm on to something with getting some touch support implemented, I have it working on the iOS simulator. Check out the fork (https://github.com/AStoker/ace), you currently need to build it to compile (as that is the source code), but if you follow the build instructions in the realm, it's cake. I would love some help with any improvements, as it doesn't seem that touch support is a high priority right now (but that's the benefit of open source, we can fix it ourselves). If everything looks good, I'll make a pull request to get it implemented.

**Comment by tluyben** [comment] 2015-09-29 15:33
+1 for copy/paste in iOS. The problem is the custom cursor handling? What would be a plan of attack to resolve that?

**Comment by paladox** [comment] 2015-11-19 17:52
IPhone 6 plus ios 9.2 public beta seems to work well now with ace. Scrolling works and editing works as if your on computer.

Just needs improvements in copying and pasting.

It is possible to paste and copy but very hard to do it.

**Comment by Bennimaxx** [comment] 2016-03-11 08:40
I have problems with the arrow keys on my IPad keyboard. The keyboard works fine in every environment but if I connect to my cloud 9 Server and start to programming, the arrow keys are ignored. Can I add them somewhere or how can this be fixed? I need the arrow very often while coding.

**Comment by Cameronymous** [comment] 2016-03-30 17:52
`<div id="editor" class="page-content" contenteditable="true"></div>`

Does the trick in iOS. Just can't seem to get assembly_x86 syntax highlighting to work.

**Comment by Bennimaxx** [comment] 2016-03-30 19:19
Where do I have to include this code? I thought this must be in the user.settings but there It has no HTML parts

**Comment by Cameronymous** [comment] 2016-03-31 06:36
HTML inside a WebView.

**Comment by facundomedica** [comment] 2016-07-16 13:24
Can't get it to work inside a UIWebView 👎  It starts ok, but as soon as I try to move the cursor, everything fails. I cannot write, or with @jcss-org-il solution (`<div id="editor" class="page-content" contenteditable="true"></div>`) the cursor moves outside the editor.

**Comment by realgenekim** [comment] 2016-08-18 03:44
Can someone help me solve a mystery?  The GitHub online code editor, allegedly based on Ace (https://github.com/blog/905-edit-like-an-ace), is amazing.  It runs flawlessly on the iPad, including with a Bluetooth keyboard, the arrow keys work (including Ctrl-Left Arrow, Alt-Left Arrow, etc), and performance is great, etc.  

Here's a screenshot of an iPad editing session of the README.md file of this repo: (https://github.com/ajaxorg/ace/edit/master/Readme.md)

![img_0819](https://cloud.githubusercontent.com/assets/2114462/17761357/49be16ac-64bb-11e6-8328-2e55b362340e.png)

And yet, everyone on this thread (myself included), can't get Ace to run on an iPad without problems (e.g., arrow keys don't work).  

Is GitHub running a custom version of Ace?  Is that version publicly available?  I'd love to run whatever they're running!  (Screenshot of DOM inspector confirming that it appears to be running Ace at bottom.)

Thank you so much!
G

![editing_ace_readme_md_at_master_ _ajaxorg_ace](https://cloud.githubusercontent.com/assets/2114462/17761344/34ac030a-64bb-11e6-93c6-911832e51e03.png)

**Comment by nightwing** [comment] 2016-08-21 13:59
@realgenekim from screenshot it looks like github uses a textarea on ipad

**Comment by realgenekim** [comment] 2016-08-23 18:48
@nightwing Fascinating theory!  But, if you look at the editor control, there are line numbers, Ace-like capabilities that seem like it's not just a standard HTML textarea, like tab width, text wrapping...  

Upon some closer inspection, I'm pretty sure it's something more exotic than textarea!

**Comment by nightwing** [comment] 2016-08-23 19:39
@realgenekim line numbers are only in the second screenshot, which doesn't look like ipad

**Comment by realgenekim** [comment] 2016-08-24 01:07
@nightwing Holy cow. That's so intriguing. I'll try to get some confirmation of this from someone at GitHub... but for me, I think this means I'll try doing the same.  I.e., detect at run-time whether it's an iPad, and not load Ace editor, and instead just use a textarea.

So unsatisfying, but at least it will be usable until someone comes up with a good iPad solution...  

😦

**Comment by waywaaard** [comment] 2016-08-24 06:06
Just tested this on my iPad pro and it basically shows an basic `textarea`. Maybe with auto grow.

**Comment by barneycarroll** [comment] 2016-08-24 06:13
Is it something clever like a textarea with 0 opacity & an ace editor instance positioned immediately behind it? I imagine with modern iPad performance it would be possible to persist state (inner scroll & content) almost instantly on each input event…

**Comment by waywaaard** [comment] 2016-08-24 06:17
@barneycarroll No, at least in my tests I was editing inside a normal text area without line numbers etc.

**Comment by etamponi** [comment] 2016-12-20 19:08
Hey guys! I've just created a pull request that fixes some of the issues on iOS. It provides a nice user experience, provided you've an external keyboard.

If you like it, I might think of adding additional features :)

You can see it in action on https://ipad-undo.gomix.me

Enjoy!

**Comment by IamNaN** [comment] 2016-12-20 22:02
Just using your demo and I'm seeing a problem with the insertion point. Create a pair of quotes, for example, put the cursor between them, and start typing. It randomly jumps to the end of the line. I'm not sure if this change introduces that problem or if it was there initially.

**Comment by etamponi** [comment] 2016-12-21 00:08
Oh, thanks @IamNaN , that bug has been reported in the PR right now :) I think I know how to fix it... stay tuned on the demo :)

**Comment by episodeyang** [comment] 2017-01-11 19:46
@etamponi That look awesome! Does it work with:
1. Plug in like vim and emac?
2. IME support with CKJ？ 

Currently it looks like it messes up when you turn on IME.

**Comment by etamponi** [comment] 2017-06-17 23:08
@episodeyang I am really sorry I left you on hold on this.

Unfortunately I didn't have the time to keep working on the PR... Luckily someone else took over my work and finished it, now it is merged as #3310 if I remember correctly :)

vim was already unsupported on iOS, and the PR doesn't add support for it. I don't know enough about IME to know for sure if my PR affected it in any way, sorry!

**Comment by nightwing** [comment] 2019-11-21 11:26
Currently ace works well enough on IOS  to close this issue about the basic compatibility. If you see any bugs or missing features, please open a new issue.

**Closed by nightwing** 2019-11-21 11:26 UTC
Labels: mobile
