### ISSUE TITLE
Placehodler of Japanese input method editor is misaligned.

### ISSUE THREAD

**Issue by hoge1e3** [ajaxorg/ace#4115] opened 2019-11-21 09:57 UTC
When type japanse text via Microsoft Japanse IME, the placeholder is slightly(half of character size) right-downward from the correct place( See the attached picture ).
 
It is happened on latest (on 2019/11/21) version placed in https://ace.c9.io/, Chrome 78.0.3904.108 Windows 10. It is happend also in Firefox 70.0.1 , Edge 44.18362.449.0 .

<img width="595" alt="スクリーンショット 2019-11-21 18 41 15" src="https://user-images.githubusercontent.com/702891/69327283-a0c04300-0c90-11ea-95a3-b9af726a8fa3.png">

**Comment by hoge1e3** [comment] 2019-11-22 03:24
This symptom does not happen in other Windows10 PC , in exactly same version of chrome.

It seems to be happend when using `transform` css attribute to move textarea.ace_text-input, it does not happen when using `left` and `top`. 

I could resolved this by force use `left` and `top` although HAS_CSS_TRANSFORMS is true:
~~~
*** ace_orig.js	Fri Nov 22 12:15:30 2019
--- ace.js	Fri Nov 22 12:13:27 2019
*************** if (typeof document !== "undefined") {
*** 1240,1246 ****
      div = null;
  }
  
! if (exports.HAS_CSS_TRANSFORMS) {
      exports.translate = function(element, tx, ty) {
          element.style.transform = "translate(" + Math.round(tx) + "px, " + Math.round(ty) +"px)";
      };
--- 1240,1246 ----
      div = null;
  }
  
! if (false && exports.HAS_CSS_TRANSFORMS) {
      exports.translate = function(element, tx, ty) {
          element.style.transform = "translate(" + Math.round(tx) + "px, " + Math.round(ty) +"px)";
      };
~~~

**Comment by nightwing** [comment] 2019-11-22 08:26
Thanks for tracking down this bug, i had not managed to reproduce it after your first comment!

This happens because left/top include the padding in calculation, and transform doesn't. Until the issue is fixed in ace, you can use the workaround of setting `padding: 0` to editor container.

**Comment by hoge1e3** [comment] 2019-11-23 04:16
Thank you for your advice.
When add the following CSS rule, this problem was not happen:
~~~
.ace_editor {
    padding: 0px;
}
~~~

**Closed** 2020-03-29 17:10 UTC
