### ISSUE TITLE
In chrome for Android, the shift key acts like backspace

### ISSUE THREAD

**Issue by voidc** [ajaxorg/ace#2038] opened 2014-07-09 13:29 UTC
If you press the shift key in chrome for Android while using the ace editor, it will delete the last character just like pressing backspace.

**Comment by faloi** [comment] 2016-04-03 15:35
This is still an issue, happens to me on a Nexus 7 tablet running Android 6.0.1 and the default keyboard.

**Comment by flbulgarelli** [comment] 2016-04-03 20:47
Hi! Same poblem here. You can reproduce by entering http://alloyui.com/examples/ace-editor/real-world/, on Chrome, Android 4.4 Moto E.

**Comment by vanillajonathan** [comment] 2016-04-28 08:59
@nightwing this happens with the default keyboard which is the [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin) (Latin).

It happens both in Chrome and WebView.

**Comment by rodri042** [comment] 2016-07-28 17:52
Using SwiftKey - Android 4.4 - Chrome, I have the same problem.

**Comment by gobstones-admin** [comment] 2016-08-17 14:10
I have experimented the problem in Android 6.0.1.
Will there be a solution soon?

**Comment by vanillajonathan** [comment] 2016-08-17 14:41
Using Google Keyboard 5.1 this has gotten worse and now actually erases text when typing using swipe gestures.

**Comment by adamjimenez** [comment] 2018-03-22 10:22
I have the same issue. Also pressing enter seems to backspace before creating a new line.

**Comment by nightwing** [comment] 2018-07-27 22:38
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Closed by nightwing** 2018-07-27 22:38 UTC

**Comment by vanillajonathan** [comment] 2018-07-28 11:29
This seems to be fixed.
