### ISSUE TITLE
insert characters at the cursor and run to another location

### ISSUE THREAD

**Issue by sujiangyin** [ajaxorg/ace#4374] opened 2020-09-01 09:39 UTC
i found the same problem,there are reason for:
This happens because the font is not monospace, ace supports only monospace fonts for now.

how to set the right font in windows?

**Comment by sujiangyin** [comment] 2020-09-07 08:17
> i found the same problem,there are reason for:
> This happens because the font is not monospace, ace supports only monospace fonts for now.
> 
> how to set the right font in windows?

everybody can give me one answer？help please

**Comment by nightwing** [comment] 2020-09-07 16:31
Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,

**Comment by sujiangyin** [comment] 2020-09-08 03:31
> Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,

on  https://ace.c9.io/ everything is normal，on my page i had cover the css rule like:

.ace-container {
    font-family: 'Monaco';
    
	@font-face {
		font-family: 'Monaco';
                src: url('Monaco.ttf');
        font-weight: normal;
               font-style: normal;
	}
}
.ace_editor {
    font-family: 'Monaco';
	@font-face {
		font-family: 'Monaco';
        src: url('Monaco.ttf');
        font-weight: normal;
        font-style: normal;
	}
}

but not help,the font may had used,but still not right. i think it may be reason by the wrong font file i download?do you kown where to download the right font file ttf? or some other reason you know? thank.

**Comment by sujiangyin** [comment] 2020-09-08 08:20
> > Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,
> 
> on https://ace.c9.io/ everything is normal，on my page i had cover the css rule like:
> 
> ```
> .ace-container {
>     font-family: 'Monaco';
>     
> 	@font-face {
> 		font-family: 'Monaco';
>                 src: url('Monaco.ttf');
>                 font-weight: normal;
>                font-style: normal;
> 	}
> }
> .ace_editor {
>     font-family: 'Monaco';
> 	@font-face {
> 		font-family: 'Monaco';
>                 src: url('Monaco.ttf');
>                 font-weight: normal;
>                 font-style: normal;
> 	}
> }
> ```
> 
> but not help,the font may had used,but still not right. i think it may be reason by the wrong font file i download?do you kown where to download the right font file ttf? or some other reason you know? thank.

i found the problem。now i can use monaco.ttf cover my font，but manaco it have the same bug.i use  Font detection tool to find what font is used. now，what font is right？**manaco or monospace?**

**Comment by sujiangyin** [comment] 2020-09-08 08:40
> > > Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,
> > 
> > 
> > on https://ace.c9.io/ everything is normal，on my page i had cover the css rule like:
> > ```
> > .ace-container {
> >     font-family: 'Monaco';
> >     
> > 	@font-face {
> > 		font-family: 'Monaco';
> >                 src: url('Monaco.ttf');
> >                 font-weight: normal;
> >                font-style: normal;
> > 	}
> > }
> > .ace_editor {
> >     font-family: 'Monaco';
> > 	@font-face {
> > 		font-family: 'Monaco';
> >                 src: url('Monaco.ttf');
> >                 font-weight: normal;
> >                 font-style: normal;
> > 	}
> > }
> > ```
> > 
> > 
> > but not help,the font may had used,but still not right. i think it may be reason by the wrong font file i download?do you kown where to download the right font file ttf? or some other reason you know? thank.
> 
> i found the problem。now i can use monaco.ttf cover my font，but manaco it have the same bug.i use Font detection tool to find what font is used. now，what font is right？**manaco or monospace?**

i had tried manaco and monospace fonts,only manaco.ttf take effect，monospace's ttf not effect. can you give a right monospace's ttf  file ,where to download??
i tried http://xiazai.zol.com.cn/detail/46/457577.shtml ,but it not right

**Comment by sujiangyin** [comment] 2020-09-08 08:59
> Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,

new finds，i use my **Font detection tool** to detect the font on https://ace.c9.io/build/kitchen-sink.html,it use the font **consola**,but that not found any bug,and i replace my project font to **consola**, it still exist,why?

**Comment by sujiangyin** [comment] 2020-09-08 09:07
> > Do you see the issue on https://ace.c9.io/? If no some css rule on your page may be changing the font. try finding that rule,
> 
> new finds，i use my **Font detection tool** to detect the font on https://ace.c9.io/build/kitchen-sink.html,it use the font **consola**,but that not found any bug,and i replace my project font to **consola**, it still exist,why?

there is all my config:

`let ace = require('ace-builds');
            require("ace-builds/src-min-noconflict/mode-json5");
            require("ace-builds/src-min-noconflict/theme-monokai");
            require("ace-builds/src-min-noconflict/ext-searchbox");

            require("ace-builds/src-min-noconflict/ext-language_tools");
            // require("ace-builds/src-min-noconflict/ext-spellcheck");
            // require("ace-builds/src-min-noconflict/ext-beautify");
            // require("ace-builds/src-min-noconflict/ext-emmet");
            //  require("ace-builds/src-min-noconflict/ext-error_marker");
            // require("ace-builds/src-min-noconflict/ext-static_highlight");

            this.aceEditor = ace.edit(this.$refs.ace, {
                fontSize: 12, // 编辑器内字体大小
                theme: this.themePath, // 默认设置的主题
                mode: this.modePath, // 默认设置的语言模式
                tabSize: 2, // 制表符设置为 4 个空格大小
                // highlightActiveLine: true,
                value: this.codeValue,
                // autoScrollEditorIntoView: true,
                maxLines: 26,
                minLines: 26
            });
            // this.aceEditor.find('ops-coffee', {  
            //     backwards: false,  
            //     wrap: false,  
            //     caseSensitive: false,  
            //     wholeWord: false,  
            //     regExp: false  
            // });  
            this.aceEditor.session.setMode('ace/mode/json5');
            this.aceEditor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });
            // 高亮显示搜索到的内容
            this.aceEditor.findAll();
            // this.aceEditor.replace('ops-coffee.cn'); 
            // this.aceEditor.replaceAll('ops-coffee.cn');
            this.aceEditor.setShowPrintMargin(false); //设置打印线`

**Comment by andrewnester** [comment] 2022-06-02 12:57
Duplicate of this https://github.com/ajaxorg/ace/issues/460

**Closed by andrewnester** 2022-06-02 12:57 UTC
Labels: needs-triage, no-autoclose
