### ISSUE TITLE
Can't always place cursor at end of line when line wrapping is on

### ISSUE THREAD

**Issue by at055612** [ajaxorg/ace#4400] opened 2020-10-19 16:28 UTC
When wrapping is on AND the last word at the end of the visual wrapped line is immediately followed by punctuation you cannot position the cursor at the end of the visual line, only in front of the last char.  If the word at the end is followed by a space then it works fine.

See this jsfiddle https://jsfiddle.net/4ynoqhux/ .  At the end of the first visual line, you cannot position the cursor after `elit` because the next char is a `.`.  At the end of the visual line below however, you can place the cursor after `cursus` as this is followed by a space char.

I am pretty sure this is not expected behaviour.  I noticed the same thing happening when the next char is a `-`.

This was seen in Ace 1.4.12

**Comment by at055612** [comment] 2022-05-09 16:26
This is still an issue in 1.4.14.  I have updated the jsfiddle https://jsfiddle.net/sL17zat3/1/

This screen grab shows the inability to select to the end of the word.  You cannot also place the cursor at the end of this word.

![image](https://user-images.githubusercontent.com/22818309/167454671-7ace93d6-0df6-4c9c-b8ae-ca2ca8bf7150.png)

**Comment by andrewnester** [comment] 2022-06-02 10:24
This is a duplicate of this https://github.com/ajaxorg/ace/issues/4579

**Closed by andrewnester** 2022-06-02 10:24 UTC
Labels: needs-triage, bug
