### ISSUE TITLE
Highlighter highlights all lines inside folded regions 

### ISSUE THREAD

**Issue by annikovk** [ajaxorg/ace#4687] opened 2022-05-05 10:26 UTC
I have serveral big folded regions (several thousand lines) stay one after another: 
![image](https://user-images.githubusercontent.com/12910542/166903198-43021e16-8793-45a7-ac62-27fe8c968657.png)

Once I search something, highlighter is invoked to highlight all of the found strings: https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/searchbox.js#L266

During the highlighting process, it takes editor's visible rows, and draws single line markers for every found range within visible rows. 

So, the problem is the fact that Ace thinks that rows inside folded regions are visible and tries to add markers for all of them:

![image](https://user-images.githubusercontent.com/12910542/166905273-63d5983f-6c6e-4a09-9b34-997d06cf4a73.png)

This causes UI freezes during the search: https://github.com/annikovk/IntelliJ-Log-Analyzer/issues/11
The only workaround I found is to unfold all regions, which is not acceptable.

**Comment by andrewnester** [comment] 2022-05-09 11:06
@annikovk could you please provide a minimal code so we can easier reproduce this issue? Thank you

**Comment by annikovk** [comment] 2022-05-23 03:54
@andrewnester have you been able to reproduce that? 
Is it a confirmed bug now?

**Comment by andrewnester** [comment] 2022-05-29 16:47
@annikovk you mentioned
> The only workaround I found is to unfold all regions, which is not acceptable.

How does unfolding help in this case? These selected word elements are still there, right?

**Comment by annikovk** [comment] 2022-05-30 03:48
I am trying to eliminate  the freeze. And the freeze happens in case there are thousands of selected words inside the folded region, which is inside visible area of the editor

unfolding helps to move selected elements out of visible region, so they are removed from DOM

Let me know if it is needed to describe that in more details with screenshots.

**Comment by andrewnester** [comment] 2022-05-30 09:35
Okay, got it!
I guess we indeed should just have 1 selected word dom element when the code is collapsed, there is no need to have them overlap.
I guess the reason we have is not to add / remove dom elements when code folds for performance reasons but it also seems like it already causes performance issues :)

I’ll try to work on PR for this

**Comment by andrewnester** [comment] 2022-05-30 12:12
@annikovk could you please check if your issue is solved here? https://raw.githack.com/andrewnester/ace/bug/4687/kitchen-sink.html

**Comment by annikovk** [comment] 2022-05-30 14:01
Yes, 100% working as expected. Thank you!

**Comment by andrewnester** [comment] 2022-05-30 16:22
We just merged the PR and released new 1.5.2 version containing the fix

**Closed by andrewnester** 2022-05-30 16:22 UTC
Labels: p2, effort/medium, pending-release
