### ISSUE TITLE
Text in the ACE editor sometimes shows up as a unicode box when you: highlight, right click, and try to do a "search google for"

### ISSUE THREAD

**Issue by brew4321** [ajaxorg/ace#2740] opened 2015-10-31 18:58 UTC
I was using khan academy, which I think uses this editor, and I noticed this glitch, and took a screen shot:
![search google for question mark](https://cloud.githubusercontent.com/assets/15134841/10865387/0fb040ce-7fcf-11e5-89da-3a0bfd5cc7de.jpg)

**Comment by aoaaxy** [comment] 2016-02-06 22:39
[This line of code](https://github.com/ajaxorg/ace/blob/ab0fff7c8df97dc4f3d7fb252022e7dba3f67942/lib/ace/keyboard/textinput.js#L120) is causing that specific unicode char (the second char in text.data) to be selected and appear there in `Search Google for "x"`. Seems by design though. 

Figured it out by having selected the text `items` (and doing a Copy, then RMB) and `t` would appear there instead of that unicode char - but this only happens on my modified attempts to try to make it select the actual selected text via `text.data=host.getCopyText()` + `text.select()` called within doCopy [right here](https://github.com/ajaxorg/ace/blob/ab0fff7c8df97dc4f3d7fb252022e7dba3f67942/lib/ace/keyboard/textinput.js#L287)
I'm still failing in my attempts though :)

**Comment by nightwing** [comment] 2018-07-27 23:23
this is fixed by https://github.com/ajaxorg/ace/pull/3635

**Closed by nightwing** 2018-07-27 23:23 UTC
