### ISSUE TITLE
Backslash (\)

### ISSUE THREAD

**Issue by stormit** [ajaxorg/ace#3470] opened 2017-12-05 15:20 UTC
Hello,

I have a problem with this library. I uses it for a CSS field. When my css code has the Backslash character, it will be removed after saving. Could you please help me check it?

Thank you!

**Comment by nightwing** [comment] 2017-12-05 18:52
Hi
this can be caused by not encoding/decoding the value correctly when saving and depends on the way you are saving it.
Could you show the code you use to save and load the value?

**Comment by nightwing** [comment] 2018-01-08 13:34
Closing, but please comment if you still see this issue

**Closed by nightwing** 2018-01-08 13:34 UTC
