### ISSUE TITLE
editor.navigateLineEnd() navigates to the end of row instead of end of line

### ISSUE THREAD

**Issue by MehbubRashid** [ajaxorg/ace#4461] opened 2021-03-03 15:23 UTC
Hi, i have setwrapmode enabled and when the editor window is small width, navigateLineEnd() function moves the cursor to the end of current row instead of the current line!

![ace-issue](https://user-images.githubusercontent.com/34944930/109828357-c0e9fa80-7c66-11eb-9767-a2239fe7a114.PNG)

**Comment by MehbubRashid** [comment] 2022-05-09 16:16
leave a commen

**Comment by andrewnester** [comment] 2022-06-02 09:14
Closing as duplicate of this https://github.com/ajaxorg/ace/issues/2858

**Closed by andrewnester** 2022-06-02 09:14 UTC
Labels: needs-triage, bug
