### ISSUE TITLE
Ace editor getValue newline format?

### ISSUE THREAD

**Issue by easytrader** [ajaxorg/ace#3214] opened 2017-02-12 02:31 UTC
Ace editor only accept \n and \\" setting: You can see setValue's content has \n and \\" tag.
```
var editor1 = ace.edit("editor1");
editor1.setTheme("ace/theme/twilight");
editor1.getSession().setMode("ace/mode/python");
editor1.setFontSize(15);
editor1.setValue("def main():\n    # Your code goes here\n\nif __name__ == \"__main__\":\n    main()");
```
But when I use` editor1.getValue()`to get value from ace editor. It will get non \n tag like below:
```
def main():
    # Your code goes here

if __name__ == "__main__":
    main()
```
But How to use non \n's value to editor1.setValue again. I want to implement the function that can modify old code store in database. The code will store editor1.getValue() into database. So it will be wrong to editor1.setValue(
```
def main():
    # Your code goes here

if __name__ == "__main__":
    main()
```
)

How to solve this? Thank you very much.

**Comment by nightwing** [comment] 2017-02-12 13:41
This is a duplicate of https://github.com/ajaxorg/ace/issues/3215
If you want to change \n in js you can use JSON.stringify(editor1.getValue()), but you shouldn't do that modify python code instead.

**Closed by nightwing** 2017-02-12 13:41 UTC

**Comment by easytrader** [comment] 2017-02-12 13:56
It not just lack of \n.
How should I do with \"?

Thank you.

**Comment by nightwing** [comment] 2017-02-12 13:57
JSON.stringify handles that

**Comment by easytrader** [comment] 2017-02-12 14:06
I use JSON.stringify ,it will become?
`editor1.setValue(&quot;def main():\n    # Your code goes here\n\nif __name__ == \&quot;__main__\&quot;:\n    main()&quot;);`

**Comment by nightwing** [comment] 2017-02-12 14:14
Then do not call setValue, change https://github.com/easytrader/StrategyWebsite/blob/master/templates/strategy_page.html#L33 to 
`<div id="editor1">{{strategy.strategy}}</div>`

**Comment by easytrader** [comment] 2017-02-12 14:22
wow amazing. nightwing you really help me a lot.
Thank you very much.
