### ISSUE TITLE
Way too much files are generated when using webpack

### ISSUE THREAD

**Issue by BlueskyFR** [ajaxorg/ace#4073] opened 2019-09-23 07:02 UTC
When using webpack-resolver.js, one file is generated by webpack for each language and theme.
This is not acceptable to have to deploy over 100 files just for ace.

Any solution to fix this and have only one files containing ace entirely?

Thanks in advance!

**Comment by nightwing** [comment] 2019-09-23 11:20
Including all modes in the main bundle would make it too large, the currently available alternative is to explicitly load the modes and files you want with require and not load webpack-resolver.js

But what is the drawback of deploying many optional files?

**Comment by simkessy** [comment] 2021-03-30 04:42
Im seeing the same issue, what's the point of the webpack-resolver, is it necessary?

**Comment by andrewnester** [comment] 2022-09-14 14:04
Closing as a duplicate of https://github.com/ajaxorg/ace/issues/4772

**Closed by andrewnester** 2022-09-14 14:04 UTC
Labels: p1, bug
