### ISSUE TITLE
RTL linebreaks

### ISSUE THREAD

**Issue by dometto** [ajaxorg/ace#3840] opened 2018-11-28 15:27 UTC
After merging #3658 I have the impression RTL support is almost complete in ACE. Remaining problem: at the moment, pressing enter while on an RTL line incorrectly produces a new LTR line.

Looking at the source, the RTL extension is supposed to prevent that with this function:
https://github.com/ajaxorg/ace/pull/3658/files#diff-39037390fecdb74f84f14bc14e4a5e1dR85
But that function never appears to be called (when I add a debug statement to it, it doesn't appear when I insert a newline on an RTL line). Am I doing something wrong, or is this a bug?

**Comment by nightwing** [comment] 2018-11-28 16:08
Thanks for reporting this issue, it was caused by a typo in the code adding change event handler.
This should be fixed by https://github.com/ajaxorg/ace/pull/3842 .
Please let us know about any other feature requests or issues you find!

**Closed** 2018-11-28 16:08 UTC
