### ISSUE TITLE
Fullscreen Command in ForEach

### ISSUE THREAD

**Issue by miyakedev** [ajaxorg/ace#3246] opened 2017-03-26 03:08 UTC
I want integer the example of demo/scrollable-page.html but after put the code my ace editor not work

script from scrollable-page
```
require.config({paths: { "ace" : "../lib/ace"}});
require(["ace/ace", "ace/ext/themelist"], function(ace) {
var $ = document.getElementById.bind(document);
var dom = require("ace/lib/dom");
//add command to all new editor instaces
require("ace/commands/default_commands").commands.push({
    name: "Toggle Fullscreen",
    bindKey: "F11",
    exec: function(editor) {
        var fullScreen = dom.toggleCssClass(document.body, "fullScreen")
        dom.setCssClass(editor.container, "fullScreen", fullScreen)
        editor.setAutoScrollEditorIntoView(!fullScreen)
        editor.resize()
    }
})
// create first editor
var editor = ace.edit("editor");
editor.setTheme("ace/theme/twilight");
editor.session.setMode("ace/mode/javascript");
editor.renderer.setScrollMargin(10, 10);
editor.setOptions({
    // "scrollPastEnd": 0.8,
    autoScrollEditorIntoView: true
});
var count = 1;
function add() {
    var oldEl = editor.container
    var pad = document.createElement("div")
    pad.style.padding = "40px"
    oldEl.parentNode.insertBefore(pad, oldEl.nextSibling)
    var el = document.createElement("div")
    oldEl.parentNode.insertBefore(el, pad.nextSibling)
    count++
    var theme = themes[Math.floor(themes.length * Math.random() - 1e-5)]
    editor = ace.edit(el)
    editor.setOptions({
        mode: "ace/mode/javascript",
        theme: theme,
        autoScrollEditorIntoView: true
    })
    editor.setValue([
        "this is editor number: ", count, "\n",
        "using theme \"", theme, "\"\n",
        ":)"
    ].join(""), -1)
    scroll()
}
function scroll(speed) {
    var top = editor.container.getBoundingClientRect().top
    speed = speed || 10
    if (top > 60 && speed < 500) {
        if (speed > top - speed - 50)
            speed = top - speed - 50
        else
            setTimeout(scroll, 10, speed + 10)
        window.scrollBy(0, speed)
    }
}
var themes = require("ace/ext/themelist").themes.map(function(t){return t.theme});
window.add = add;
window.scroll = scroll;
});
```

My ForEach code :
`    var highlight = ace.require("ace/ext/static_highlight");
  
    function qsa(sel) {
        return Array.apply(null, document.querySelectorAll(sel));
    }
  
    qsa("#ide").forEach(function (codeEl) {
        var editor = ace.edit(codeEl);
        editor.setTheme("ace/theme/monaco");
        editor.getSession().setMode("ace/mode/" + codeEl.getAttribute("lang"));
        editor.getSession().setUseWrapMode(true);
        editor.setOption("wrap", "off");
        editor.setOption("selectionStyle", "text");
        editor.setFontSize(16);
        editor.getSession().setTabSize(4);
        editor.getSession().setUseSoftTabs(true);
        editor.setDisplayIndentGuides(false);
        editor.setShowPrintMargin(false);
        editor.setAutoScrollEditorIntoView(true);
        editor.setReadOnly(true);
        editor.setOption("maxLines", 30);
  	editor.setOption("minLines", 1);
        editor.setOption("scrollPastEnd", true);
    });`

**Comment by nightwing** [comment] 2017-04-09 13:44
Were you able to get this to work? Closing this issue since it is not a bug report.
But i can help you to debug your code if you create a demo online (e.g. plnkr.co/jsbin).

**Closed by nightwing** 2017-04-09 13:44 UTC
