### ISSUE TITLE
`ace_gutter` & `ace_scroller` overflow the editor

### ISSUE THREAD

**Issue by j1hwang** [ajaxorg/ace#3817] opened 2018-11-08 07:20 UTC
Hi, I am using `ace-v1.4.1/ace.js` and having a problem stated in the title.
I put my settings below. Hope it is helpful a bit.

```
@editor.setOptions(
  {
    tabSize: 2,
    useSoftTabs: true,
    highlightActiveLine: false,
    maxLines: Infinity
  }
)
```

<img width="115" alt="screen shot 2018-11-08 at 4 18 24 pm" src="https://user-images.githubusercontent.com/8577077/48183442-04bbe600-e372-11e8-915e-a2b3c28c4527.png">
(first line disappears)
  
  
<img width="266" alt="screen shot 2018-11-08 at 4 12 14 pm" src="https://user-images.githubusercontent.com/8577077/48183208-44ce9900-e371-11e8-8831-81b26e916c90.png">

As shown in the images above,
when typing a new line, the first line goes outside(overflows) the editor div (`div.ace_editor`).

After typing the line, when pressing enter, the editor turns normal.
Any thoughts?

**Comment by nightwing** [comment] 2018-11-08 20:29
Old versions of ace have this issue on new versions of chrome due to a change in the way chrome scrolls hidden textarea into view on input.
This should be fixed with the latest version of ace.

**Comment by nightwing** [comment] 2018-11-20 23:40
Sorry, i didn't get notification when you have changed the version in the comment.

Is the page where this happens somewhere public, seeing it would greatly help me in reproducing the issue. 

Also could you confirm that you see this on chrome?

**Comment by 40thieves** [comment] 2019-05-29 16:53
I think we are also seeing this issue. We're on Ace v1.4.4, although the screenshots below were taken with v1.4.3. The issue definitely happens on Chrome, and our users are reporting that it happens on Firefox too.

Unfortunately we have been unable to reproduce it ourselves, so I can't get you a broken example, however you can sign up for a free account on overleaf.com to test it for yourself.

Here's a couple of screenshots that I managed to get from a user (I've redacted the personal info).

`.ace_editor` is correctly positioned:

<img width="1301" alt="Screen Shot 2019-05-16 at 11 38 50" src="https://user-images.githubusercontent.com/424411/58575056-45f5e380-8239-11e9-970c-15e0eb574c56.png">

`.ace_scroller` is incorrectly positioned:

<img width="1300" alt="Screen Shot 2019-05-16 at 11 38 27" src="https://user-images.githubusercontent.com/424411/58575070-4d1cf180-8239-11e9-8679-685897708a34.png">

(`.ace_gutter` is also affected in a similar way).

Looking at the CSS, it appears that `.ace_editor` is relatively positioned and `.ace_scroller` is absolutely positioned, with `left` applied to offset the gutter. However, for some reason (that I don't understand) `.ace_scroller` is not positioned relative to it's parent.

The only thing we can think of is that a `translate` is being applied, but we can't find a reasonable way that would happen.

Any ideas?

**Comment by nightwing** [comment] 2019-05-29 18:22
@40thieves I have used sharelatex, and after merger use overleaf from time to time.
Using transform is normal, ace uses it on hi-dpi screens or when browser zoom is larger than 150%.

But the issue you see seems different. Do you call editor.resize after changing the size of the container div? I tried adding breakpoint for that function on overleaf but it didn't get hit

**Comment by 40thieves** [comment] 2019-05-30 14:07
> Using transform is normal, ace uses it on hi-dpi screens or when browser zoom is larger than 150%.

Yep, sorry I didn't mean to imply that `transform` was bad. Was just that the only way we could think that the div was positioned there was due to a transform being applied incorrectly.

As mentioned we haven't been able to reproduce ourselves, so I can't really say what causes the problem. The user in the screenshots just refreshed the page (and the divs are correctly aligned), typed a bit and it would suddenly jump out of position.

I suppose it's possible that we're somehow changing the size of the container and **not** calling `resize`. But I don't think that was necessary for the issue to occur.

Sorry that I can't give better reproduction instructions :(

**Comment by nightwing** [comment] 2019-05-30 21:10
@40thieves perhaps i misunderstood the issue, since very little of ace is visible on screenshots, is the issue that large scrollbar is shown despite text being only in the black area or something else?

Also I've noticed that there are several versions of ace included on sharelatex page, which is likely to cause conflicts. And the version 1.2.9 (included in the page) used to trigger a browser bug where typing in out of view textarea would scroll the parent overflow hidden element. So it may be worth to check `scrollTop` and `scrollLeft` on `.ace_editor` and its parent node, if the user who have made the screenshots manages to reproduce the issue again.

But before that it would be very good to remove the old versions of ace, depending on loading order they can have hard to debug interactions with one another.

**Comment by nightwing** [comment] 2019-06-04 10:35
Sorry i got misguided by several ace folders in https://github.com/overleaf/web/tree/master/public/js.

> What's even more puzzling to me is that, looking at the CSS for .ace_scroller, it has a left: 67px rule. If the parent element (.ace_editor) is a relatively positioned element, how can the child element end up being shifted to the left, considering it has a positive left value?

The only possible explanation i see is the scrollLeft change. That's the only way that both scroller and scrollbar-v would be shifted by the same amount.

A way to replicate something similar is to run the following in the browser, then click on some none focusable element outside of the editor

```js
if (window.t) t.remove()
t=document.createElement("textarea")
t.style = "position:absolute;right:-230px"
el= document.querySelector(".ace_editor")
el.style.overflow = "hidden"
el.appendChild(t)
window.onmousedown = function(e) { console.log(e); e.preventDefault(); t.focus() }
el.scrollLeft=0
```

I am not saying that this is the exact cause of the issue, but perhaps something else is triggering the same bug in the browser, making it scroll the overflow:hidden element.

As you are already changing the  `overflow` property when showing comments could you try to set it  to `visible` always.

**Comment by 40thieves** [comment] 2019-06-12 13:20
Thanks for that suggestion. It got us thinking about how `scrollLeft` might be applied and we had another look at the screenshots I took from an affected user.

It seems that the `.ace_text-input` is somehow getting a `left` and `top` value **as well** as a `transform` value:

<img width="287" alt="left-top-and-translate" src="https://user-images.githubusercontent.com/424411/59347411-78f5a800-8d0c-11e9-9a01-1d3772048cb6.png">

If I manually add a `left` value to the textarea (via dev tools) then I can reproduce the issue in the kitchen sink:

![Kapture 2019-06-12 at 12 33 07](https://user-images.githubusercontent.com/424411/59348356-c5da7e00-8d0e-11e9-94c2-289437c6be98.gif)

Comparing against what I see in the dev tools (on my unaffected page), I believe the textarea should only get `transform` value if the browser supports transforms. Having a quick look through the code, I think that value is applied in this method: https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L629-L677.

I did spot that `left` & `top` are applied to the textarea under some other circumstances (possibly when the contextmenu is opened?): https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L571-L574

Thanks again for your help here. Happy to provide more information if needed.

**Comment by nightwing** [comment] 2019-06-12 20:13
Thanks for investigating this! Both left and transform are getting applied when pressing the right button, and then pressing left button without releasing the right one. I've opened a pull request that should solve this issue https://github.com/ajaxorg/ace/pull/3986.

**Comment by 40thieves** [comment] 2019-06-14 10:49
Great, thanks! The attached PR does look like it would solve the issue 👍 Thanks again for your work on this

**Comment by 40thieves** [comment] 2019-06-14 11:26
Sorry I forgot to ask - do you have an estimate of when this might get into a release?

**Closed** 2019-06-14 11:47 UTC

**Comment by nightwing** [comment] 2019-06-14 12:08
The new version will be released on monday.
