### ISSUE TITLE
the Cursor Doesn't Line up with Non-Monospace Fonts

### ISSUE THREAD

**Issue by inyourface34456** [ajaxorg/ace#4645] opened 2022-03-02 21:29 UTC
https://user-images.githubusercontent.com/62214409/156452916-ada65ae6-3e10-4177-9778-33f3d2e34298.mp4

For some reason, The cursor does not line up with Serif and Sans-Serif fonts.  I do not know why or how this happens, but it may be related to #4586.  is a fix possible?

System information:
Google Chrome: 98.0.4758.107 (Official Build) (64-bit)
Revision: a2ef32d533baed737df9fc2ed8d505405ecf0c66-refs/branch-heads/4758@{#1167}
Platform: 14388.61.0 (Official Build) stable-channel octopus
Firmware Version: Google_Fleex.11297.296.0
ARC: 8186397
JavaScript: V8 9.8.177.11

Video:
https://user-images.githubusercontent.com/62214409/156452943-2d457823-df84-4406-b518-ee29cc3fa90d.mp4

**Comment by inyourface34456** [comment] 2022-03-09 21:07
It seems to have worked itself out?  Do not know when this happened, as I have not restarted my computer since then.

**Comment by winter1215** [comment] 2022-04-18 15:10
same

**Comment by inyourface34456** [comment] 2023-03-24 15:35
I have also found that it considers non mono space fonts about 2 times wider then they really are.

**Comment by akoreman** [comment] 2023-10-24 09:21
Thanks for opening this issue, this is a result of the bigger issue of lacking support for variable width characters in Ace. Closing this issue as a duplicate of #460.

**Closed by akoreman** 2023-10-24 09:21 UTC
