### ISSUE TITLE
Static highlight

### ISSUE THREAD

**Issue by ManiacTwister** [ajaxorg/ace#2367] opened 2015-02-24 14:40 UTC
Hello,

I would really like to have the line wrap feature available in the static_highlighter. Currently long lines are just wrapped by css word-wrap which breaks the padding of the gutter.

**Comment by nightwing** [comment] 2015-02-24 17:04
This should be fixed by https://github.com/ajaxorg/ace/pull/2370

**Comment by ManiacTwister** [comment] 2015-02-26 16:44
@nightwing I cannot confirm this. This is how it looks like on master branch:
http://data.s7t.de/master_branch.jpg

An this is misc branch:
http://data.s7t.de/misc_branch.jpg

Also the the line numbers aren't right aligned anymore now and the backgrpund color is also broken.

**Comment by nightwing** [comment] 2015-02-26 18:01
@ManiacTwister could you show the code you used for screenshot i don't see this issue on https://rawgit.com/ajaxorg/ace/misc/demo/static-highlighter.html

**Comment by ManiacTwister** [comment] 2015-02-26 18:04
@nightwing I used https://github.com/ajaxorg/ace/tree/master/demo/static-highlighter

**Comment by nightwing** [comment] 2015-02-28 16:44
It was assuming editor.css is included in the page. Pushed a fix for that.

**Comment by ManiacTwister** [comment] 2015-03-01 17:46
Looks good now. Thanks

**Closed** 2015-03-17 22:47 UTC

**Comment by bzvyagintsev** [comment] 2022-08-10 19:55
Hi! How to correctly set `wrap: true` option in `static_highlight` on the client? Setting this option doesn't affect line wrapping anyhow:
```
<!-- load ace -->
<script src="../src/ace.js"></script>
<!-- load ace static_highlight extension -->
<script src="../src/ext-static_highlight.js"></script>
<script>
    var highlight = ace.require("ace/ext/static_highlight")
    var dom = ace.require("ace/lib/dom")
    function qsa(sel) {
        return Array.apply(null, document.querySelectorAll(sel));
    }

    qsa(".code").forEach(function (codeEl) {
        highlight(codeEl, {
            mode: codeEl.getAttribute("ace-mode"),
            theme: codeEl.getAttribute("ace-theme"),
            firstLineNumber: 1,
            showGutter: codeEl.getAttribute("ace-gutter"),
            trim: true,
            **wrap: true**
        }, function (highlighted) {

        });
    });
</script>
```

and:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/12235087/184001887-1294c35e-f619-46cc-8cf6-bfe6bccc8086.png">

If I set this option on session in `highlight.renderSync` method inside `ext-static_highligh`: `session.setOption('wrap', true)`, `$renderLine` will return empty lines with groups:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/12235087/184007815-aa5f71c6-1f27-4bd0-95d1-a2086466549b.png">

And if put console.log(splits) inside this.$renderLine:
```
var splits = this.session.getRowSplitData(row);
console.log(splits)
```

I see that splits are correctly calculated:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/12235087/184006049-7e5a82e7-9a35-4627-aa51-25dc6e1302bd.png">

**Comment by nightwing** [comment] 2022-08-11 05:41
@bzvyagintsev static_highlight does not generate splits and relies on browser to wrap the text. 

It should be wrapped by default because of 
```
.ace_static_highlight {
    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', 'Droid Sans Mono', monospace;
    font-size: 12px;
    white-space: pre-wrap;
}
```

css rule included in default styles.

**Comment by bzvyagintsev** [comment] 2022-08-11 09:21
Is it possible to pass the wrap limit inside `static_highlight` and implement wrapping by splits? Is it feasible?

I see that splits are correctly generated if set `wrap: true` on the session. But the output is empty.

**Comment by bzvyagintsev** [comment] 2022-08-15 13:30
@nightwing can you point me where I can try to implement this inside Ace? Where should I start investigating why static highlight returns empty lines when the wrap option is set to true?

**Comment by nightwing** [comment] 2022-08-16 21:41
Most likely it is an issue with Element mock used in static_highlight https://github.com/ajaxorg/ace/blob/master/src/ext/static_highlight.js#L22

**Comment by bzvyagintsev** [comment] 2022-08-19 11:06
Seems that:

> Element mock used in static_highlight

works as expected, but the issue comes from [$renderLine](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/layer/text.js#L508). It looks like `lineEl` that is already appended to the parent starts to being overwritten (maybe with `lineEl = this.$createLineElement()` inside [renderWrappedLine](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/layer/text.js#L425)). 

@nightwing do you have an idea what could be happening?

**Comment by bzvyagintsev** [comment] 2022-08-24 00:26
@nightwing indeed issue come from Element mock. If I'm right, the problem is that in the [appendChild](https://github.com/ajaxorg/ace/blob/master/src/ext/static_highlight.js#L19) the `this.textContent` is combined with string concatenation, while the [renderLine](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/layer/text.js#L508) supposes to have access to line elements through the link.
