### ISSUE TITLE
Ace.d.ts: Autocomplete not working because of missing type declaration of TextInput.setAriaOptions

### ISSUE THREAD

**Issue by MGJamJam** [ajaxorg/ace#5049] opened 2023-02-02 17:54 UTC
### Describe the bug

For ace-builds version >= 1.14.0: 
In https://github.com/ajaxorg/ace/pull/5008 a new function `setAriaOptions` was added to `TextInput`, but not added to the Ace.d.ts file. When using Ace Editors autocomplete with Typescript, a TypeError is thrown because autocomplete calls setAriaOptions, but this function it is not defined in the Ace.d.ts file. 

### Expected Behavior

Autocomplete working normally. 

### Current Behavior

TypeError is thrown. Autocomplete stops working. No Popup is shown. The first entered key gets duplicated when typing in Editor. 

<img width="500" alt="Screenshot 2023-01-30 at 07 53 15" src="https://user-images.githubusercontent.com/48029745/216399479-fa6d8617-59aa-47a1-b9a2-dc87ac361d93.png">

### Reproduction Steps

Use Ace-Editor with Typescript and ace-builds >= 1.14.0. Set options to enable autocomplete
`enableBasicAutocompletion: true,
  enableLiveAutocompletion: true,`
and type into the editor. 

### Possible Solution

Add setAriaOptions() to Ace.d.ts:

```
export interface TextInput {
    resetSelection(): void;
    setAriaOption(activeDescendant: string, role: string): void;
  }
```

### Ace Version / Browser / OS / Keyboard layout

Ace Version >= 1.14.0

**Comment by Sid-80** [comment] 2023-02-11 15:40
Will you please assign this task to me ?

**Comment by Sid-80** [comment] 2023-02-11 15:58
#5057 will you please check it.

**Comment by nightwing** [comment] 2023-02-13 21:12
looks like this issue is caused by loading ace.js and ext-language_tools.js from different versions of ace, because  https://github.com/ajaxorg/ace-builds/blob/v1.14.0/src-noconflict/ace.js#L4022 does not match with what is shown in the stacktrace

**Closed** 2023-02-16 14:33 UTC
Labels: p2, effort/small, bug, good first issue, pending-release
